// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DiceController from "./dice_controller"
application.register("dice", DiceController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import TableController from "./table_controller"
application.register("table", TableController)
